### ISSUE TITLE
feature: press space than press a movement command

### ISSUE THREAD

**Issue by brownman** [kaievns/pentix.rb#2]
there is a bug - that i will be detail below, but adding my suggested  feature will also eliminate the bug:
FEATURE
adding the option to press space to fast dropping the figure - 
but with the option catching another movement commands such as - go one step to the right/left.
it will solve the problem of having to wait to  a shape to reach a cave like shape of the static blocks/ground.

BUG 
a shape isn't put where u last saw it but it will be saved in the big matrix on top of the highest block,
say u have a house and u tried locate the figure on the floor - it will be saved on the roof if there is a roof above the floor.
## 

u can add a feature of catching bugs - in the log files - with a textual drawings of the game.
than it will be easier to report a bug.

**Comment by kaievns** [comment]
Hi brownman,

Regarding the feature, what you ask is called "soft drop" and it is unsporty, so it won't appear in this implementation.

Regarding the bug, I don't see the problem, aren't figures supposed to stick to the highest interrupting block?

Regarding debugging and log files. Debugging is for sissies, I use specs instead https://github.com/MadRabbit/pentix.rb/blob/master/spec/lib/glass_spec.rb

**Comment by brownman** [comment]
"Debugging is for sissies"

:))
soooo right !

b.t.w
your code is concise !

suggestion:
make an irb console more usefull for the game dev
if takes care also for block's colors.

**Comment by brownman** [comment]
imagine cave like shape made of blocks

read sign "-" as empty space
read sign "#" as block
read sign "0" as falling figure

BUG: can't place figure under the higher floor - just try and cry/laugh :)

--------0 falling figure

"####"  higher floor
"#"
"##########"   floor

**Comment by brownman** [comment]
suggestion: 
use chipmunk physics to increase fun level.

**Comment by kaievns** [comment]
could you use markdown code blocks?

```
kinda like this
```

I think I understand what you mean now. Will fix it on the weekend

**Comment by kaievns** [comment]
Fixed! 00018c93cd060a5e080cf57b867f976ac14810d5
